googleapis/signet

lib/signet/oauth_2/client.rb
Fixing issue where options' keys are required to be passed as symbols, but which eventually causes an error when attempting to compare with string keys for URI query values.
For demonstration/reproduction of the error in the current signet version, see this gist:
https://gist.github.com/swifthand/7c35c2c56619db5abbfd
=> Fixes OAuth2 authorization_uri assignement error.

lib/signet.rb, lib/signet/oauth_1/client.rb, lib/signet/oauth_1/server.rb, lib/signet/oauth_2/client.rb
This PR addresses several warnings that occur in the library. These warnings occur in projects that use signet. The warnings addressed are:
* assigned but unused variable
* instance variable not initialized
* shadowing outer local variable
You can see these warnings by enabling the -w flag when running the specs.
`$ RUBYOPT=-w rake spec`
(There are several more warnings in the specs that are not addressed in this PR, as they will not show up when simply using the library.)
=> Fix warnings

lib/signet/oauth_2/client.rb
The inline comment example has the wrong argument keys. This PR fixes them.
=> Fix Signet::OAuth2::Client.new example arguments

signet.gemspec
The tests pass in ruby 1.9, 2.1, and 2.2.
=> The extlib gem is never used, so remove it from the gemspec.

spec/signet/oauth_1/client_spec.rb, spec/signet/oauth_1/credential_spec.rb, spec/signet/oauth_1/server_spec.rb, spec/signet/oauth_1/services/google_spec.rb, spec/signet/oauth_1/signature_methods/hmac_sha1_spec.rb, spec/signet/oauth_1/signature_methods/plaintext_spec.rb, spec/signet/oauth_1/signature_methods/rsa_sha1_spec.rb, spec/signet/oauth_1_spec.rb, spec/signet/oauth_2/client_spec.rb, spec/signet/oauth_2_spec.rb, spec/signet_spec.rb, spec/spec_helper.rb, spec/spec_helper_spec.rb
also, I found that running some test one by one fails because of missing necessary files,
so some are added.
tests pass
``
$ bundle exec rspec
``
tests fail
``
$ bundle exec rspec spec/signet/oauth_1/signature_methods/hmac_sha1_spec.rb
``
=> Remove redundant code

lib/signet/oauth_2/client.rb
This patch fixes timestamp normalization on 32-bit systems where it fails with the following error:
`gems/signet-0.7.2/lib/signet/oauth_2/client.rb:1183:in 'normalize_timestamp': Invalid time value 1453993753 (RuntimeError)`
Quick analysis confirms that the issue is caused by the fact that unix timestamp on a 32-bit system is a `Bignum` while `normalize_timestamp` handles only `Fixnum`. Here is a little bit of irb o confirm the conjecture:
```
2.3.0 :001 > Time.now.to_i
=> 1453995813 
2.3.0 :002 > Time.now.to_i.class
=> Bignum 
2.3.0 :003 > MAXFIXNUM=(2**(0.size*8 -2) -1)
=> 1073741823 
```
The modification is really simple and basically adds parsing of the Bignum timestamps in addition to Fixnums which are already supported. It's also worth mentioning that current master fails two of the …
=> Support for unix timestamps normalization on 32-bit system

lib/signet/oauth_2/client.rb
Ruby 2.4.0 unifies Fixnum and Bignum into Integer.
https://bugs.ruby-lang.org/issues/12005
Fix following deprecated warnings in Ruby 2.4.0+.
- `warning: constant ::Fixnum is deprecated`
- `warning: constant ::Bignum is deprecated`
Thanks.
=> Integer Unification for Ruby 2.4.0+

lib/signet/oauth_2/client.rb
By nil-ing the expires_at attribute, next time expires_at is accessed
through the reader, it will get recalculated.
As it is currently, when refreshing the access_token, the issued_at,
expires_in would get updated, but expires_at may still indicate that the
token has expired.
=> The "expires_at" attribute should also be recalculated on refresh

lib/signet/oauth_2/client.rb, spec/signet/oauth_2/client_spec.rb
:scope as a value in options passed to generate_access_token_request is not even documented. But at the same time it discards if the object has been set up correctly with a scope. The Google Cloud fluentd plugin calls @client.authorization.fetch_access_token! (which inherits from Signet::OAuth2::Client) but the scope is then not copied over into the access token request, causing requests to Cloud Logging to fail. With this patch I was able to pass in a refresh token properly through the client's environment.
=> Add the configured scope to the access token request.

.travis.yml, lib/signet/oauth_2/client.rb, signet.gemspec, spec/signet/oauth_2/client_spec.rb
This version of ruby-jwt requires specification of the algorithm (see
https://github.com/jwt/ruby-jwt/pull/184) for more information.
=> Support ruby-jwt 2.0

lib/signet/oauth_2/client.rb
=> Signet::OAuth2::Client#decoded_id_token should take optional &keyfinder block for JWT.decode

.travis.yml, signet.gemspec
Googleauth, which depends on this library, currently still (attempts to) support Ruby 1.9.
=> Support Ruby 1.9.3

lib/signet/errors.rb, lib/signet/oauth_2/client.rb, spec/signet/oauth_2/client_spec.rb
Currently 5xx errors return a Signet::AuthorizationError which is misleading
I added a Signet::RemoteServerError so they can be distinguished
=> Handle 5xx errors with RemoteServerError

lib/signet/oauth_2/client.rb, spec/signet/oauth_2/client_spec.rb
Fix #75
[oauth2client](https://github.com/google/oauth2client) which is the Python library for OAuth 2.0 by Google returns `False` in this case.
https://github.com/google/oauth2client/blob/v4.1.2/oauth2client/client.py#L635-L645
In the same way,  I think that `.expires_within?` of `Signet::OAuth2::Client` should return `false` when `expires_at` is `nil`. Also, in order to avoid this problem, it is a wrong solution to set `.expires_in` to value which is different from the actual one.
=> Fix "Missing token endpoint URI" Error

lib/signet/oauth_2/client.rb, spec/signet/oauth_2/client_spec.rb
This pull request fixes a subtle issue where if a user provides `expires_in` and `issued_at`, the `expires_at` is calculated with `Time.now`, causing the client to never be expired.
Examples:
Current result
```ruby
client.update_token!(
expires_in: 3600,
issued_at: '2018-08-24T00:00:00Z'
)
client.expires_at # => 2018-08-24T13:00:00
client.expired? # => false
```
Expected result
```ruby
client.update_token!(
expires_in: 3600,
issued_at: '2018-08-24T00:00:00Z'
)
client.expires_at # => 2018-08-24T01:00:00
client.expired? # => true
```
Notice that `self.issued_at =` is moved above the expires code block, as `expires_in=` checks if `self.issued_at` is set or not.
=>  Calculate expires_at from issued_at, if provided

CHANGELOG.md, lib/signet/errors.rb, lib/signet/oauth_2/client.rb, lib/signet/version.rb, spec/signet/oauth_2/client_spec.rb
Currently unexpected status errors return a Signet::AuthorizationError which is misleading
I added a Signet::UnexpectedStatusError so they can be distinguished
=> Handle unexpected status errors

lib/signet/oauth_2/client.rb
Fix the documentation for `Signet::OAuth2::Client#audience`. It looks like it was copied from `#issuer`.
=> Fix audience documentation

lib/signet/oauth_2/client.rb, spec/signet/oauth_2/client_spec.rb
Currently, we can not consider the possibility that the type of `payload["aud"]` is an array.
According to the specification of open-id-connect, I think that it is better to support the array.
https://openid.net/specs/openid-connect-core-1_0.html#IDToken
> aud
REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.
=> Support the array of `aud`

CHANGELOG.md, README.md, lib/signet/version.rb, signet.gemspec
* Update gem requirements so Ruby 2.4.0 is the minimum.
* Remove the Ruby version warning.
* Update documentation.
* Update changelog and version for 0.12.0.
=> Require Ruby 2.4

lib/signet/version.rb, signet.gemspec
This is probably "technically" a breaking change, although I'd be surprised if people are depending on the version constant being a module. This is needed to get this library under releasetool.
=> Normalize the version constant

CHANGELOG.md, lib/signet/version.rb
* This version now requires Ruby 2.4.
* Support array values of the "aud" field.
* Normalize the version constant to match related gems.
Note: Autorelease may not be set up properly for this repo yet. I'm going to try to use it, but if it fails, I'll release manually after the PR is merged.
=> Release signet 0.12.0

.kokoro/release/signet.cfg
Update the config to match the corresponding configs in google-cloud-ruby.
Notes:
* I'm pretty sure `TRAMPOLINE_SCRIPT` is needed. The error message I'm currently getting from the kokoro job suggests what happens when it is missing.
* I'm slightly less sure about `PACKAGE` but all the individual package configs in google-cloud-ruby include it, so I assume it is needed to identify which package to publish.
* I'm not sure at all about the extra `keystore_resource`s. They are present in google-cloud-ruby's configs. Are they needed?
=> Update kokoro config for release job

Rakefile
Two additional fixes to the signet release task in the rakefile.
* Renamed the internal release task from `release` to `release_gem`. This is because `release` is already taken by the bundler rake plugin. When running the tasks, it appears the bundler task is taking precedence (possibly because it is defined first). In any case, we need our custom task to be executed instead because it handles rubygems credentials the way we want, so I renamed it to avoid the collision. (This issue does not affect the google-cloud-ruby rakefile because the toplevel rakefile never brings in the bundler plugin. Only the subdirectory rakefiles use the bundler tasks.)
* The `tag` parameter to the task was formatted one way when passed in but parsed another way, so some of the strings internally were formatted …
=> fix: Avoid rakefile task collisions, and fix tag format

rakelib/repo_metadata.rb
Keeping consistency with google-cloud-ruby gems. Changes:
googleapis.dev/ruby/signet/0.1.0 to
googleapis.dev/ruby/signet/v0.1.0
=> add v to version url

CHANGELOG.md, lib/signet/version.rb
* Support Faraday 1.x
<details><summary>Commits since previous release</summary><pre><code>commit 23d733541eb9e741ff6279a4a975bea4e505eb06
Author: Joe Stein <joeaarons@gmail.com>
Date:   Mon Feb 24 15:29:38 2020 -0500
feat: support Faraday 1.x
commit 3ce8da40d99c7631d8655fdc249cca9271e18d47
Author: Graham Paye <paye@google.com>
Date:   Tue Oct 29 16:08:24 2019 -0700
add v to version url (#157)
commit 05e3f52dba07d54ea2229e5e8eb4c4485cc8cc4f
Author: Graham Paye <paye@google.com>
Date:   Thu Oct 17 20:26:47 2019 -0700
chore: run linkinator on merges to master (#154)
commit 3e041a52ef4d7c3592cc1af79c02b6c997872739
Author: Graham Paye <paye@google.com>
Date:   Thu Oct 17 18:12:55 2019 -0700
chore: use docker images from google-cloud-ruby (#156)
commit d2cbe633e86e2ac852168c61a3ca5149658a9148 …
=> Release signet 0.13.0

lib/signet/oauth_2/client.rb, spec/signet/oauth_2/client_spec.rb
This assertion is used to specify the audience that should be included in identity tokens signed and returned by Google's OAuth endpoint. This change will be used in conjunction with related changes in the googleauth gem to provide support for fetching and authenticating with ID tokens.
=> feat: Support for the "target_audience" assertion used by Google's OAuth endpoint

lib/signet/oauth_1.rb, spec/signet/oauth_1_spec.rb
Uses `uri.query_values(Array)` instead of `uri.query_values.to_a` to avoid deduplicating query parameters. See https://www.rubydoc.info/gems/addressable/Addressable/URI#query_values-instance_method
=> Fix the bug with duplicate/array params

.rubocop.yml, CHANGELOG.md, README.md, lib/signet.rb, lib/signet/oauth_1.rb, lib/signet/oauth_1/client.rb, lib/signet/oauth_1/credential.rb, lib/signet/oauth_1/server.rb, lib/signet/oauth_1/signature_methods/rsa_sha1.rb, lib/signet/oauth_2.rb, lib/signet/oauth_2/client.rb, rakelib/devsite_builder.rb, rakelib/repo_metadata.rb, signet.gemspec
* Updated the gemspec's `required_ruby_version` to `>= 2.5`
* Updated `google-style` to `~> 1.25.1`
* Resolved all rubocop issues
=> feat: Drop support for Ruby 2.4 and add support for Ruby 3.0

signet.gemspec
Remediation
Upgrade addressable to version 2.8.0 or later. For example:
gem "addressable", ">= 2.8.0"
Always verify the validity and compatibility of suggestions with your codebase.
Details
GHSA-jxhc-q857-3j6g
high severity
Vulnerable versions: > 2.3.0, <= 2.7.0
Patched version: 2.8.0
Impact
Within the URI template implementation in Addressable, a maliciously crafted template may result in uncontrolled resource consumption, leading to denial of service when matched against a URI. In typical usage, templates would not normally be read from untrusted user input, but nonetheless, no previous security advisory for Addressable has cautioned against doing this. Users of the parsing capabilities in Addressable but not the URI template capabilities are unaffected.
Patches
The vulnerability was …
=> Upgrade addressable gem from 2.3 to 2.8 to remediate vulnerability

lib/signet/oauth_1/client.rb, lib/signet/oauth_1/server.rb, lib/signet/oauth_2/client.rb, signet.gemspec, spec/signet/oauth_1/client_spec.rb, spec/signet/oauth_1/server_spec.rb, spec/spec_helper.rb
Faraday 2.0 has been released earlier this year, and since this is one of the most popular gems (according to [bestgems](https://bestgems.org/gems/signet)) using Faraday as a dependency, it would be great if it would support the latest major version!
This PR removes a condition that would allow an array to be provided to the server as a request, because that simply doesn't work anymore. The "bug" was introduced [here](https://github.com/iMacTia/signet/commit/bb449aa64ca4fcbe2d7485370f871f444c388888#diff-cc62e9a1887143d3c39c443e1906d3edf397f78e6c098d9ce21a49a2b0bdaeddR150-R158) and the test around that (./spec/signet/oauth_1/server_spec.rb:157) has only been passing because calling `#method` on an Array causes an `ArgumentError`, rather than actually testing the request is complete. This …
=> Relax Faraday dependency version to allow 2.x

lib/signet/oauth_2/client.rb, spec/signet/oauth_2/client_spec.rb
When user credentials are fetched and refreshed, the OAuth server returns granted scopes. This change exposes those scopes in the credentials object
=> feat: Expose Granted Scopes while fetching credentials
